workflows:
  android-workflow:
    name: Android APK
    environment:
      flutter: stable
    scripts:
      - flutter create --platforms=android .
      - flutter pub get      
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
