name: conozco_comprendo_acompano
description: Una ruta para acompañar el desarrollo integral de los niños de 0 a 5 años. No buscamos cambiar al niño. Buscamos comprenderlo para acompañarlo.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
